# Generated by Django 5.1.1 on 2025-08-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_foodpurchase_options_dish_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Default Menu', max_length=255),
        ),
    ]
