import { Product } from '@/types/product';

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: '1',
    inventoryId: '1',
    name: 'Maize',
    price: 4000,
    imageUrl: 'https://picsum.photos/seed/maize-grain/300/300',
    productCategoryId: '',
    category: 'Food',
  },
  {
    id: '2',
    inventoryId: '2',
    name: 'Lentils',
    price: 500,
    imageUrl: 'https://picsum.photos/seed/lentils-bowl/300/300',
    productCategoryId: '',
    category: 'Food',
  },
  {
    id: '3',
    inventoryId: '3',
    name: 'Beans',
    price: 400,
    imageUrl: 'https://picsum.photos/seed/kidney-beans/300/300',
    productCategoryId: '',
    category: 'Food',
  },
  {
    id: '4',
    inventoryId: '4',
    name: 'Sukuma',
    price: 50,
    imageUrl: 'https://picsum.photos/seed/kale-leaf/300/300',
    productCategoryId: '',
    category: 'Food',
  },
  {
    id: '5',
    inventoryId: '5',
    name: 'Milk',
    price: 70,
    imageUrl: 'https://picsum.photos/seed/milk-bottle/300/300',
    productCategoryId: '',
    category: 'Beverages',
  },
  {
    id: '6',
    inventoryId: '6',
    name: 'Water',
    price: 50,
    imageUrl: 'https://picsum.photos/seed/water-bottle/300/300',
    productCategoryId: '',
    category: 'Beverages',
  },
  {
    id: '7',
    inventoryId: '7',
    name: 'Eggs',
    price: 600,
    imageUrl: 'https://picsum.photos/seed/farm-eggs/300/300',
    productCategoryId: '',
    category: 'Food',
  },
  {
    id: '8',
    inventoryId: '8',
    name: 'Beef',
    price: 800,
    imageUrl: 'https://picsum.photos/seed/beef-cut/300/300',
    productCategoryId: '',
    category: 'Food',
  },
];
