# Generated by Django 5.1.1 on 2025-08-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('WageWorker', 'Wage Worker'), ('SiteManager', 'Site Manager'), ('SystemAdmin', 'System Admin')], default='WageWorker', max_length=255),
        ),
    ]
