# Generated by Django 5.1.1 on 2025-08-24 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_code',
            field=models.CharField(default='+254', max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid country code (e.g. +254)', regex='^\\+\\d{1,3}$')]),
        ),
    ]
