# Generated by Django 5.1.1 on 2025-08-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
