# Generated by Django 5.1.1 on 2026-06-22 17:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20)),
                ('transaction_method', models.CharField(choices=[('stk_push', 'STK Push'), ('b2c', 'B2C'), ('c2b', 'C2B'), ('b2b', 'B2B'), ('cash', 'Cash')], max_length=20)),
                ('transaction_purpose', models.CharField(blank=True, choices=[('expense_payment', 'Expense Payment')], max_length=50, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_channel', models.CharField(blank=True, choices=[('pochi', 'Pochi'), ('paybill', 'Paybill'), ('till', 'Till')], max_length=20, null=True)),
                ('receiver_number', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_account', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('transaction_status_details', models.TextField(blank=True, null=True)),
                ('sender_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reconciliation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('callback_resp', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
