# Generated by Django 5.1.1 on 2026-06-22 17:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherLoan',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('chama', 'Chama'), ('bank', 'Bank'), ('sacco', 'Sacco'), ('loan_apps', 'Loan Apps'), ('others', 'Others')], max_length=20)),
                ('loan_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_repayment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLoan',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('chama', 'Chama'), ('bank', 'Bank'), ('sacco', 'Sacco'), ('loan_apps', 'Loan Apps'), ('others', 'Others')], max_length=20)),
                ('loan_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_repayment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
