# ==================== APPLICATION CONFIGURATION ====================
spring.profiles.active=development
spring.service.name=biashara-book
spring.application.name=mvp-biashara-book

# ==================== JWT SECURITY CONFIGURATION ====================
spring.security.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
spring.security.jwt.expiration=86400000

# ==================== SERVER CONFIGURATION ====================
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# ==================== LOGGING CONFIGURATION ====================
# Default Logging Format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} | Severity=%-5p | MicroService=${spring.service.name} | %m %n
logging.level.com.example.mvp=DEBUG
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG